# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
#
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot
# https://github.com/dependabot

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"

    schedule:
      timezone: "Europe/Kyiv"
      interval: "weekly"
      # time: "04:00"
