branches:
  - name: "main"
  - name: "dev"
    prerelease: true

repositoryUrl: "git@github.com:yukal/slim-validator.git"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
