# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://github.com/actions/checkout
# https://github.com/marketplace/actions/action-for-semantic-release

name: Develop

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      # - name: Build
      #   run: go build -v ./...

      # - name: Benchmark
      #   run: go test -bench=. -benchmem ./...

      - name: Test
        run: go test -cover ./...
